export const SUPABASE_URL = "https://ropicyaczuzygewryopk.supabase.co";
export const SUPABASE_ANON_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJvcGljeWFjenV6eWdld3J5b3BrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MTM1NTg2NDgsImV4cCI6MjAyOTEzNDY0OH0.8UxvUhQljE0WLm-BQZ00ZUCKxVglNQiLg5xQAdQGnDg";
